#ifndef ACTIONSTYPE_H
#define ACTIONSTYPE_H

enum ActionType : int {
	// 1
	MAIN_MENU,
	// 1.1
	CARD_INSERT_MENU,
	CARD_INSERT_BLOCKED,
	CARD_INSERT_OUTDATED,
	// 1.3
	USER_MENU,
	// 1.3.1
	CASH_WITHDRAWAL_MENU,
	CASH_WITHDRAWAL_WITHDRAWED,
	CASH_WITHDRAWAL_NO_CASH,
	CASH_WITHDRAWAL_NO_BALANCE,
	// 1.3.2
	CASH_ADD_MENU,
	CASH_ADD_ADDED,
	// 1.3.3
	MONEY_TRANSFER_MENU1,
	MONEY_TRANSFER_MENU2,
	MONEY_TRANSFER_NO_BALANCE,
	MONEY_TRANSFER_WRONG_CARD,
	MONEY_TRANSFER_TRANSFERED,
	// 1.3.4
	GET_BALANCE_PRINTED,
	// 1.3.5
	PIN_CHANGE_PRINTED,


	NONE // for technical purposes
};

#endif // ACTIONSTYPE_H
