#ifndef ACTIONSTYPE_H
#define ACTIONSTYPE_H

enum ActionType : int {
	// 1
	MAIN_MENU,
	// 1.1
	CARD_INSERT_MENU,
	CARD_INSERT_BLOCKED,
	CARD_INSERT_OUTDATED,
	// 1.3
	USER_MENU,
	// 1.3.1
	CASH_WITHDRAWAL_MENU,
	CASH_WITHDRAWAL_WITHDRAWED,
	CASH_WITHDRAWAL_NO_CASH,
	CASH_WITHDRAWAL_NO_BALANCE,
	// 1.3.2
	CASH_ADD_MENU,
	CASH_ADD_ADDED,
	// 1.3.3
	MONEY_TRANSFER_MENU1,
	MONEY_TRANSFER_MENU2,
	MONEY_TRANSFER_NO_BALANCE,
	MONEY_TRANSFER_WRONG_CARD,
	MONEY_TRANSFER_TRANSFERED,
	// 1.3.4
	GET_BALANCE_PRINTED,
	// 1.3.5
	PIN_CHANGE_PRINTED,

	// TO
	TO_MAIN_MENU,
	TO_NEW_CARD_MENU,
	TO_NEW_CARD_EXISTS,
	TO_NEW_CARD_CREATED,
	TO_CARD_BLOCK_MENU,
	TO_CARD_BLOCK_NOT_EXISTS,
	TO_CARD_BLOCK_ALREADY_BLOCKED,
	TO_CARD_BLOCK_EXPIRED,
	TO_CARD_BLOCK_BLOCKED,
	TO_CARD_UNBLOCK_MENU,
	TO_CARD_UNBLOCK_NOT_BLOCKED,
	TO_CARD_UNBLOCK_UNBLOCKED,
	TO_MONEY_INSERT_MENU,
	TO_MONEY_INSERT_INESERTED,
	TO_WORK_FINISHED,

	NONE // for technical purposes
};

#endif // ACTIONSTYPE_H
